# The URL the site will be built for
base_url = "https://rusty-ecma.com"
title = "Rusty Ecma"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# highlight_theme = "1337"
# highlight_theme = "Tomorrow"
# highlight_theme = "agola-dark"
# highlight_theme = "ascetic-white"
# highlight_theme = "axar"
# highlight_theme = "ayu-dark"
# highlight_theme = "ayu-light"
# highlight_theme = "ayu-mirage"
# highlight_theme = "base16-ocean-dark"
# highlight_theme = "base16-ocean-light"
# highlight_theme = "bbedit"
# highlight_theme = "boron"
# highlight_theme = "charcoal"
# highlight_theme = "cheerfully-light"
# highlight_theme = "classic-modified"
# highlight_theme = "demain"
# highlight_theme = "dimmed-fluid"
# highlight_theme = "dracula"
# highlight_theme = "gray-matter-dark"
# highlight_theme = "gruvbox-dark"
# highlight_theme = "gruvbox-light"
# highlight_theme = "idle"
# highlight_theme = "inspired-github"
# highlight_theme = "ir-white"
# highlight_theme = "kronuz"
# highlight_theme = "material-dark"
# highlight_theme = "material-light"
# highlight_theme = "monokai"
# highlight_theme = "one-dark"
# highlight_theme = "solarized-dark"
# highlight_theme = "solarized-light"
# highlight_theme = "subway-madrid"
# highlight_theme = "subway-moscow"
# highlight_theme = "visual-studio-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true



[extra]
# Put all your custom variables here
sam_menu = [
    { text = "book", link = "https://rusty-ecma.github.io/rusty-ecma-book/" },
    { text = "RESS", link = "/ress" },
    { text = "RESSA", link = "/about" },
    { text = "RESAST", link = "/resast" },
    { text = "RESW", link = "/resw" }
]